"""neuraltree_compile — Write wiki pages to .neuraltree/wiki/.

Karpathy LLM-Wiki pattern: the LLM compiles raw sources into structured,
interlinked wiki pages. This tool handles the file operations:
  - Write a compiled wiki page (Claude writes the content, tool writes the file)
  - Auto-update .neuraltree/wiki/_INDEX.md
  - Append to .neuraltree/wiki/log.md

The Skill decides WHAT to compile. This tool handles WHERE and HOW it's stored.
Algorithm in Tool, Judgment in Claude.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from fastmcp import FastMCP

from neuraltree_mcp.validation import validate_project_root, validate_within_root


# Frontmatter patterns
_FM_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
_NAME_RE = re.compile(r"name:\s*(.+)")
_DESC_RE = re.compile(r"description:\s*(.+)")


def _wiki_dir(root: Path) -> Path:
    """Get the wiki directory, create if needed."""
    d = root / ".neuraltree" / "wiki"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _slugify(topic: str) -> str:
    """Convert a topic name to a safe filename slug."""
    slug = topic.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "untitled"


def _extract_fm_field(content: str, field: str) -> str:
    """Extract a field from YAML frontmatter."""
    fm = _FM_RE.search(content)
    if not fm:
        return ""
    pat = re.compile(rf"{re.escape(field)}:\s*(.+)")
    m = pat.search(fm.group(1))
    return m.group(1).strip() if m else ""


def _rebuild_index(wiki_dir: Path) -> str:
    """Rebuild _INDEX.md from all wiki pages."""
    entries = []
    for f in sorted(wiki_dir.iterdir()):
        if f.is_symlink() or not f.name.endswith(".md") or f.name in ("_INDEX.md", "log.md"):
            continue
        try:
            content = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        name = _extract_fm_field(content, "name") or f.stem.replace("-", " ").title()
        desc = _extract_fm_field(content, "description") or ""
        sources_str = _extract_fm_field(content, "source_count") or "0"
        entries.append({
            "file": f.name,
            "name": name,
            "description": desc,
            "sources": sources_str,
        })

    lines = [
        "# Wiki Index\n",
        "",
        f"> {len(entries)} compiled pages | Auto-generated by neuraltree_compile",
        "",
    ]
    for e in entries:
        desc = f" — {e['description']}" if e["description"] else ""
        lines.append(f"- [{e['name']}]({e['file']}){desc}")

    return "\n".join(lines) + "\n"


def _append_log(wiki_dir: Path, operation: str, topic: str, details: str = "") -> None:
    """Append an entry to log.md. Uses append mode for safe concurrent writes."""
    log_path = wiki_dir / "log.md"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    entry = f"## [{ts}] {operation} | {topic}\n"
    if details:
        entry += f"{details}\n"
    entry += "\n"

    is_new = not log_path.exists()
    with open(log_path, "a", encoding="utf-8") as fh:
        if is_new:
            fh.write("# Wiki Log\n\n> Chronological record of all wiki operations.\n\n")
        fh.write(entry)


def register(mcp: FastMCP) -> None:

    @mcp.tool()
    def neuraltree_compile(
        topic: str,
        content: str,
        sources: list[str],
        project_root: str = ".",
        update_existing: bool = True,
    ) -> dict:
        """Compile a wiki page from LLM-synthesized content.

        Writes a structured wiki page to .neuraltree/wiki/{slug}.md,
        updates the wiki index, and appends to the operation log.

        The content should be Claude-written markdown with:
        - Frontmatter (name, description, source_count, last_compiled)
        - Body with synthesized knowledge
        - ## Sources section listing source files
        - ## Related section with cross-links to other wiki pages

        Args:
            topic: The topic/entity name (e.g. "Authentication", "Database Schema").
            content: Full markdown content for the wiki page (written by Claude).
            sources: List of source file paths that were synthesized into this page.
            project_root: Project root directory.
            update_existing: If True, overwrite existing page. If False, error on conflict.

        Returns:
            dict with path (relative), slug, sources_count, index_updated, log_entry.
        """
        try:
            root = validate_project_root(project_root)
        except (ValueError, OSError) as e:
            return {"error": str(e)}

        if not topic or not topic.strip():
            return {"error": "topic is required"}
        if not content or not content.strip():
            return {"error": "content is required"}

        slug = _slugify(topic)
        wiki_dir = _wiki_dir(root)
        page_path = wiki_dir / f"{slug}.md"

        # Check for conflict
        if page_path.exists() and not update_existing:
            return {"error": f"Page already exists: {slug}.md (set update_existing=True to overwrite)"}

        # Validate page path stays within root
        try:
            validate_within_root(page_path, root)
        except ValueError as e:
            return {"error": str(e)}

        # Check if this is an update or first compile (BEFORE writing)
        is_update = page_path.exists()

        # Ensure content has frontmatter — inject if missing
        if not content.strip().startswith("---"):
            ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            fm = (
                f"---\n"
                f"name: {topic}\n"
                f"description: Compiled wiki page for {topic}\n"
                f"source_count: {len(sources)}\n"
                f"last_compiled: {ts}\n"
                f"---\n\n"
            )
            content = fm + content

        # Write the page
        page_path.write_text(content, encoding="utf-8")

        # Rebuild index
        index_content = _rebuild_index(wiki_dir)
        (wiki_dir / "_INDEX.md").write_text(index_content, encoding="utf-8")

        # Append log
        operation = "update" if is_update else "compile"
        details = f"- Sources: {len(sources)} files\n- Slug: {slug}.md"
        _append_log(wiki_dir, operation, topic, details)

        rel_path = str(page_path.relative_to(root))
        return {
            "path": rel_path,
            "slug": slug,
            "sources_count": len(sources),
            "index_updated": True,
            "log_appended": True,
            "wiki_dir": str(wiki_dir.relative_to(root)),
        }

    @mcp.tool()
    def neuraltree_wiki_read(
        project_root: str = ".",
    ) -> dict:
        """Read the wiki index and stats.

        Returns the current state of the compiled wiki:
        page count, index content, log tail, and page list.

        Args:
            project_root: Project root directory.

        Returns:
            dict with page_count, pages, index_content, recent_log.
        """
        try:
            root = validate_project_root(project_root)
        except (ValueError, OSError) as e:
            return {"error": str(e)}

        wiki_dir = root / ".neuraltree" / "wiki"
        if not wiki_dir.is_dir():
            return {
                "page_count": 0,
                "pages": [],
                "index_content": "",
                "recent_log": "",
                "exists": False,
            }

        pages = []
        for f in sorted(wiki_dir.iterdir()):
            if f.is_symlink() or not f.name.endswith(".md") or f.name in ("_INDEX.md", "log.md"):
                continue
            content = ""
            try:
                content = f.read_text(encoding="utf-8", errors="replace")
            except OSError:
                pass
            name = _extract_fm_field(content, "name") or f.stem
            desc = _extract_fm_field(content, "description") or ""
            pages.append({"file": f.name, "name": name, "description": desc})

        # Read index
        idx_path = wiki_dir / "_INDEX.md"
        index_content = ""
        if idx_path.exists():
            index_content = idx_path.read_text(encoding="utf-8", errors="replace")

        # Read last 10 log entries
        log_path = wiki_dir / "log.md"
        recent_log = ""
        if log_path.exists():
            log_text = log_path.read_text(encoding="utf-8", errors="replace")
            # Get last 10 entries (## headers)
            entries = re.split(r"(?=^## )", log_text, flags=re.MULTILINE)
            recent = entries[-10:] if len(entries) > 10 else entries
            recent_log = "".join(recent).strip()

        return {
            "page_count": len(pages),
            "pages": pages,
            "index_content": index_content,
            "recent_log": recent_log,
            "exists": True,
        }
